# Bastion Plugin Configuration

admins:
  - "QED"
  - "DeekyJ"
  - "spraguerilla"

wave:
  # Time in seconds to wait after a wave is completed before starting the next one.
  completion_delay_seconds: 120
  # Time in seconds for the countdown before a new wave becomes active.
  preparation_delay_seconds: 10
  # Maximum duration in seconds for a wave before it times out and fails.
  wave_duration_seconds: 300

  # Parameters for the wave difficulty generation heuristic.
  difficulty_scaling:
    # The target average difficulty for the first wave.
    starting_average_difficulty: 1.0
    # The percentage increase in target difficulty for each subsequent wave.
    average_difficulty_increase_percent: 5.0
    # The number of consecutive failed attempts to improve the mob set before halting.
    max_failed_swaps: 50


village:
  # Barrier dimensions (in blocks)
  barrier:
    radius: 80  # Changed from size: 200 to radius: 80 (160x160 area)
    height: 256
    # Barrier visualization settings
    dome_shape: true  # Use 3D dome instead of cylindrical wall
    show_underground: true  # Show particles below ground in air blocks

economy:
  rewards:
    wave_completion: 5
    boss_wave_completion: 20
    villager_saved: 3


# Visual and sound effects
effects:
  barrier:
    visible: true
    particle_density: 1.0  # Increased for better dome visibility
    particle_spacing: 1  # Reduced spacing for denser barrier (was 2)
    update_interval: 10  # Faster updates for smoother animation (was 20)

    # Enhanced particle visibility settings
    particle_size: 4.0  # Larger particles (default was 2.0)
    particle_intensity: 3  # Number of particle effects per location
    multiple_particle_types: true  # Use DUST + FLAME + ENCHANT + FIREWORK
    particle_animation: true  # Enable pulsing/color animation effects

    # Underground cave detection settings
    max_underground_depth: 20  # How deep to check for air spaces
    debug_mode: false  # Enable debug particles and logging

    # Color settings (R,G,B format)
    primary_color: "0,255,255"    # Bright cyan
    secondary_color: "255,255,0"  # Bright yellow for animation
  spawn:
    warning_sound: true
    warning_particles: true

# Creeper explosion behavior settings
creeper_explosion:
  enabled: true
  countdown_seconds: 5  # How long creeper waits before exploding if no progress
  progress_check_interval: 20  # How often to check for progress (in ticks, 20 = 1 second)
  position_history_size: 3  # Number of recent block positions to track for progress detection

mob_ai:
  creeper_vision_radius: 10  # Creepers can detect players/villagers within 10 blocks, even through walls
  player_target_weight: 0.7  # Weight for targeting players
  villager_target_weight: 0.3  # Weight for targeting villagers
  target_switch_chance: 0.1  # Chance to switch targets
  max_target_distance: 50.0  # Maximum distance for targeting
  scan_interval_ticks: 100  # Interval for scanning targets (in ticks)

loot_table_settings:
  common_loot_probability: 0.4  # Probability of common loot dropping (increased from 0.05)
  common_loot_max_items: 8  # Maximum number of common loot items (increased from 5)
  bonus_loot_probability: 0.15  # Probability of bonus loot dropping (increased from 0.01)
  bonus_loot_max_items: 4  # Maximum number of bonus loot items (increased from 2)
  wave_scaling_base: 0.05  # Base multiplier for exponential wave scaling (x in formula: (1.0 + x)^currentWave)

# Loot tables for different mobs, including common and bonus loot.
# Common loot is dropped by all mobs, while bonus loot is rarer and more valuable.  
# enchanted books and potions will be included in bonus loot, but need 
# special handling to randomly select the enchantment/potion type.

common_loot:
  zombie: "leather,iron_nugget,gold_nugget,iron_ingot,bread,carrot,potato" # 1.0
  skeleton: "leather, oak_log,coal,bone,arrow,iron_ingot,stone,cobblestone" # 1.2
  spider: "sugar_cane,cobblestone,string,cobweb,stone,coal,iron_nugget" # 1.3
  creeper: "flint,gunpowder,iron_ingot,gold_ingot,coal" # 1.8
  enderman: "obsidian,nether_wart,ender_pearl,iron_ingot,diamond" # 2.2
  witch: "lapis_lazuli,blaze_rod,redstone,glowstone_dust,iron_ingot,gold_ingot" # 2.5
  pillager: "crossbow,iron_ingot,wooden_plank,feather" # 1.3
  stray: "tipped_arrow,emerald" # 1.4
  cave_spider: "spider_eye,cobweb" # 1.5
  phantom: "phantom_membrane,feather,diamond_sword,iron_chestplate" # 1.6
  blaze: "blaze_powder,blaze_rod,fire_charge,diamond" # 1.9
  vindicator: "iron_ingot,emerald" # 2.0
  evoker: "totem_of_undying,iron_ingot,emerald" # 3.5
  vex: "totem_of_undying,iron_ingot" # 3.7
  ravager: "totem_of_undying,emerald,diamond,iron_ingot" # 4.0

bonus_loot:
  zombie: "gravel,egg,golden_apple,cooked_beef,emerald"
  skeleton: "experience_bottle,bow,diamond,emerald"
  spider: "villager_spawn_egg,iron_boots,web,diamond,emerald"
  stray: "tipped_arrow,emerald,book"
  cave_spider: "experience_bottle,book"
  creeper: "tnt,emerald"
  blaze: "blaze_powder,blaze_rod,fire_charge,diamond"
  phantom: "phantom_membrane,feather"
  enderman: "totem_of_undying,diamond,ender_chest,shulker_box"
  witch: "ghast_tear,brewing_stand,cauldron,diamond"

# Defines the difficulty score for each mob type, used for calculating wave difficulty.
# The score is a scalar based on health, damage, speed, and special abilities.
# Zombie is the baseline at 1.0.
mob_difficulty:
  zombie: 1.0
  skeleton: 1.2
  spider: 1.3
  creeper: 1.8
  enderman: 2.2
  witch: 2.5
  pillager: 1.3
  stray: 1.4
  cave_spider: 1.5
  phantom: 1.6
  blaze: 1.9
  vindicator: 2.0
  evoker: 3.5
  vex: 3.7
  ravager: 4.0
