# Bastion Plugin Configuration

admins:
  - "QED"
  - "DeekyJ"
  - "spraguerilla"

wave:
  # UNUSED: Base number of mobs per wave (before player scaling)
  base-mob-count: 10
  # UNUSED: Additional mobs per player
  mobs-per-player: 2
  # UNUSED: Base difficulty multiplier per wave
  difficulty-multiplier: 1.5
  # UNUSED: Mob stat scaling
  scaling:
    health: 1.5
    damage: 1.5
  # UNUSED: Player count scaling
  player-scaling:
    mob-health: 0.3  # Additional 30% health per player
  # UNUSED: Wave completion requirements
  completion:
    require-all-mobs-defeated: true

village:
  # Barrier dimensions (in blocks)
  barrier:
    radius: 80  # Changed from size: 200 to radius: 80 (160x160 area)
    height: 256
    # Barrier visualization settings
    dome-shape: true  # Use 3D dome instead of cylindrical wall
    show-underground: true  # Show particles below ground in air blocks
  # UNUSED: Villager settings
  villagers:
    health-multiplier: 2.0
    regeneration:
      enabled: true
      amount: 1.0  # Hearts per second between waves

economy:
  # UNUSED: Base emerald values for different activities
  rewards:
    wave-completion: 5
    boss-wave-completion: 20
    villager-saved: 3
  # UNUSED: Trading settings
  trading:
    enhanced-trades-unlock-wave: 5
    boss-wave-special-trades: true

# Visual and sound effects
effects:
  barrier:
    # UNUSED: Barrier particle effects
    visible: true
    particle-density: 1.0  # Increased for better dome visibility
    particle-spacing: 1  # Reduced spacing for denser barrier (was 2)
    update-interval: 10  # Faster updates for smoother animation (was 20)

    # Enhanced particle visibility settings
    particle-size: 4.0  # Larger particles (default was 2.0)
    particle-intensity: 3  # Number of particle effects per location
    multiple-particle-types: true  # Use DUST + FLAME + ENCHANT + FIREWORK
    particle-animation: true  # Enable pulsing/color animation effects

    # Underground cave detection settings
    max-underground-depth: 20  # How deep to check for air spaces
    debug-mode: false  # Enable debug particles and logging

    # Color settings (R,G,B format)
    primary-color: "0,255,255"    # Bright cyan
    secondary-color: "255,255,0"  # Bright yellow for animation
  # UNUSED: Wave start effects
  spawn:
    warning-sound: true
    warning-particles: true

# Creeper explosion behavior settings
creeper-explosion:
  enabled: true
  countdown-seconds: 5  # How long creeper waits before exploding if no progress
  progress-check-interval: 20  # How often to check for progress (in ticks, 20 = 1 second)
  position-history-size: 3  # Number of recent block positions to track for progress detection

mob-ai:
  creeper-vision-radius: 10  # Creepers can detect players/villagers within 10 blocks, even through walls
  player-target-weight: 0.7  # Weight for targeting players
  villager-target-weight: 0.3  # Weight for targeting villagers
  target-switch-chance: 0.1  # Chance to switch targets
  max-target-distance: 50.0  # Maximum distance for targeting
  scan-interval-ticks: 100  # Interval for scanning targets (in ticks)

# UNUSED: Debug settings
debug:
  enabled: false
  log-wave-stats: false