# Bastion Plugin Configuration

wave:
  # Base number of mobs per wave (before player scaling)
  base-mob-count: 10
  # Additional mobs per player
  mobs-per-player: 2
  # Base difficulty multiplier per wave
  difficulty-multiplier: 1.5
  # Mob stat scaling
  scaling:
    health: 1.5
    damage: 1.5
  # Player count scaling
  player-scaling:
    mob-health: 0.3  # Additional 30% health per player
  # Wave completion requirements
  completion:
    require-all-mobs-defeated: true

village:
  # Barrier dimensions (in blocks)
  barrier:
    size: 200
  # Villager settings
  villagers:
    health-multiplier: 2.0
    regeneration:
      enabled: true
      amount: 1.0  # Hearts per second between waves

economy:
  # Base emerald values for different activities
  rewards:
    wave-completion: 5
    boss-wave-completion: 20
    villager-saved: 3
  # Trading settings
  trading:
    enhanced-trades-unlock-wave: 5
    boss-wave-special-trades: true

# Visual and sound effects
effects:
  barrier:
    visible: true
    particle-density: 0.5
  spawn:
    warning-sound: true
    warning-particles: true

# Debug settings
debug:
  enabled: false
  log-wave-stats: false