# Bastion Plugin Configuration

admins:
  - "QED"
  - "DeekyJ"
  - "spraguerilla"

wave:
  # Time in seconds to wait after a wave is completed before starting the next one.
  completion_delay_seconds: 120
  # Time in seconds for the countdown before a new wave becomes active.
  preparation_delay_seconds: 10
  # Maximum duration in seconds for a wave before it times out and fails.
  wave_duration_seconds: 300

  # Parameters for the wave difficulty generation heuristic.
  difficulty_scaling:
    # The target average difficulty for the first wave.
    starting_average_difficulty: 1.0
    # The percentage increase in target difficulty for each subsequent wave.
    average_difficulty_increase_percent: 5.0
    # The number of consecutive failed attempts to improve the mob set before halting.
    max_failed_swaps: 50


village:
  # Barrier dimensions (in blocks)
  barrier:
    radius: 80  # Changed from size: 200 to radius: 80 (160x160 area)
    height: 256
    # Barrier visualization settings
    dome_shape: true  # Use 3D dome instead of cylindrical wall
    show_underground: true  # Show particles below ground in air blocks

economy:
  rewards:
    wave_completion: 5
    boss_wave_completion: 20
    villager_saved: 3


# Visual and sound effects
effects:
  barrier:
    visible: true
    particle_density: 1.0  # Increased for better dome visibility
    particle_spacing: 1  # Reduced spacing for denser barrier (was 2)
    update_interval: 10  # Faster updates for smoother animation (was 20)

    # Enhanced particle visibility settings
    particle_size: 4.0  # Larger particles (default was 2.0)
    particle_intensity: 3  # Number of particle effects per location
    multiple_particle_types: true  # Use DUST + FLAME + ENCHANT + FIREWORK
    particle_animation: true  # Enable pulsing/color animation effects

    # Underground cave detection settings
    max_underground_depth: 20  # How deep to check for air spaces
    debug_mode: false  # Enable debug particles and logging

    # Color settings (R,G,B format)
    primary_color: "0,255,255"    # Bright cyan
    secondary_color: "255,255,0"  # Bright yellow for animation
  spawn:
    warning_sound: true
    warning_particles: true

# Creeper explosion behavior settings
creeper_explosion:
  enabled: true
  countdown_seconds: 5  # How long creeper waits before exploding if no progress
  progress_check_interval: 20  # How often to check for progress (in ticks, 20 = 1 second)
  position_history_size: 3  # Number of recent block positions to track for progress detection

mob_ai:
  creeper_vision_radius: 10  # Creepers can detect players/villagers within 10 blocks, even through walls
  player_target_weight: 0.7  # Weight for targeting players
  villager_target_weight: 0.3  # Weight for targeting villagers
  target_switch_chance: 0.1  # Chance to switch targets
  max_target_distance: 50.0  # Maximum distance for targeting
  scan_interval_ticks: 100  # Interval for scanning targets (in ticks)

loot_table_settings:
  common_loot_probability: 0.4  # Probability of common loot dropping (increased from 0.05)
  common_loot_max_items: 8  # Maximum number of common loot items (increased from 5)
  bonus_loot_probability: 0.15  # Probability of bonus loot dropping (increased from 0.01)
  bonus_loot_max_items: 4  # Maximum number of bonus loot items (increased from 2)
  wave_scaling_base: 0.05  # Base multiplier for exponential wave scaling (x in formula: (1.0 + x)^currentWave)

# Loot tables for different mobs, including common and bonus loot.
# Common loot is dropped by all mobs, while bonus loot is rarer and more valuable.  
# enchanted books and potions will be included in bonus loot, but need 
# special handling to randomly select the enchantment/potion type.

common_loot:
  # Stage 1: Basic Survival & Villager Care
  zombie: "wheat,potatoes,carrots,beetroots,raw_beef,raw_pork,oak_log,sticks,string,feathers,flint,wool,rotten_flesh,coal"
  slime: "wheat,potatoes,carrots,raw_fish,oak_log,sticks,string,feathers,wool,coal"
  spider: "wheat,beetroots,melons,raw_chicken,oak_log,sticks,string,feathers,flint,rotten_flesh,coal"
  skeleton: "raw_beef,raw_pork,raw_fish,oak_log,sticks,string,feathers,flint,wool,coal"
  # Stage 2: Infrastructure & Early Trading
  husk: "oak_log,sand,sugar_cane,books,coal,iron_ingot,pumpkin,leather,string,feathers"
  creeper: "oak_log,sand,sugar_cane,paper,coal,iron_ingot,pumpkin,leather,gunpowder"
  pillager: "sand,sugar_cane,paper,books,coal,iron_ingot,leather,string,feathers"
  magma_cube: "oak_log,sand,sugar_cane,books,iron_ingot,pumpkin,leather,magma_cream"
  # Stage 3: Iron Age & Basic Enchanting
  stray: "iron_ingot,gold_ingot,gold_nugget,diamond,leather,paper,emerald,experience_bottle,sand,spider_eye"
  cave_spider: "iron_ingot,gold_ingot,gold_nugget,diamond,paper,emerald,experience_bottle,spider_eye"
  zombified_piglin: "iron_ingot,gold_ingot,gold_nugget,diamond,leather,emerald,experience_bottle,sand"
  # Stage 4: Advanced Magic Systems
  phantom: "lapis_lazuli,diamond,obsidian,blaze_rod,blaze_powder,nether_wart,sugar,slimeball,spider_eye,brown_mushroom,emerald,gold_ingot"
  zoglin: "lapis_lazuli,diamond,obsidian,blaze_rod,blaze_powder,nether_wart,slimeball,emerald,gold_ingot"
  vindicator: "lapis_lazuli,diamond,obsidian,blaze_powder,nether_wart,sugar,spider_eye,brown_mushroom,emerald,gold_ingot"
  # Stage 5: Master Brewing & Advanced Resources
  blaze: "ghast_tear,magma_cream,pufferfish,phantom_membrane,melon_slice,gold_nugget,nether_quartz_ore,clay,cactus,moss_block,sculk"
  enderman: "ghast_tear,magma_cream,phantom_membrane,melon_slice,gold_nugget,nether_quartz_ore,clay,moss_block,sculk,ender_pearl,obsidian"
  witch: "ghast_tear,magma_cream,pufferfish,phantom_membrane,gold_nugget,clay,cactus,moss_block,sculk,lapis_lazuli,redstone,glowstone_dust"
  wither_skeleton: "ghast_tear,magma_cream,pufferfish,phantom_membrane,nether_quartz_ore,clay,cactus,sculk,wither_skeleton_skull"
  # Stage 6: Endgame Mastery
  ravager: "ancient_debris,dragon_breath,ghast_tear,magma_cream,phantom_membrane,gold_nugget,nether_quartz_ore,clay,moss_block,sculk,diamond,emerald"
  evoker: "ancient_debris,dragon_breath,ghast_tear,pufferfish,phantom_membrane,nether_quartz_ore,sculk,totem_of_undying,emerald"
  vex: "ancient_debris,dragon_breath,phantom_membrane,nether_quartz_ore,clay,sculk,totem_of_undying"
  ghast: "ancient_debris,dragon_breath,ghast_tear,magma_cream,pufferfish,phantom_membrane,gold_nugget,nether_quartz_ore,sculk,fire_charge"

bonus_loot:
  # Stage 1: Basic Survival Bonus
  zombie: "bread,cooked_beef,golden_carrot,emerald"
  slime: "honey_bottle,cooked_cod,golden_apple,emerald"
  spider: "cobweb,fermented_spider_eye,golden_apple,emerald"
  skeleton: "bone_meal,experience_bottle,book,emerald"
  
  # Stage 2: Infrastructure Bonus
  husk: "iron_ingot,leather_helmet,golden_apple,emerald"
  creeper: "tnt,gunpowder,iron_ingot,golden_apple,emerald"
  pillager: "crossbow,iron_ingot,white_banner,emerald"
  magma_cube: "magma_block,iron_ingot,emerald"
  
  # Stage 3: Iron Age Bonus
  stray: "ice,packed_ice,arrow,emerald,book"
  cave_spider: "spider_eye,experience_bottle,emerald,book"
  zombified_piglin: "gold_ingot,golden_sword,emerald,book"
  
  # Stage 4: Advanced Magic Bonus
  phantom: "elytra,phantom_membrane,emerald,book"
  zoglin: "leather,cooked_porkchop,emerald,book"
  vindicator:  "emerald_block,emerald,book"
  
  # Stage 5: Master Brewing Bonus
  blaze: "brewing_stand,blaze_rod,book"
  enderman: "ender_chest,shulker_box,ender_pearl,book"
  witch: "cauldron,brewing_stand,book"
  wither_skeleton: "wither_skeleton_skull,totem_of_undying,book"
  
  # Stage 6: Endgame Bonus
  ravager: "saddle,lead,emerald_block,book"
  evoker: "totem_of_undying,emerald_block,emerald,book"
  vex: "totem_of_undying,phantom_membrane,emerald,book"
  ghast: "ghast_tear,fire_charge,dragon_breath,book"

# Defines the difficulty score for each mob type, used for calculating wave difficulty.
# The score is a scalar based on health, damage, speed, and special abilities.
# Zombie is the baseline at 1.0.
mob_difficulty:
  # stage 1 [1.0, 1.5)
  zombie: 1.0  # Slow, melee only, completely predictable movement
  slime: 1.1  # Easy to avoid, predictable bouncing, splits into weaker versions
  spider: 1.2  # Fast but weak damage, neutral in daylight, easy to hit
  skeleton: 1.3  # Ranged but slow projectiles, easily blocked by shields/cover
  # stage 2 [1.5, 2.2)
  husk: 1.5  # Similar to zombie but can inflict hunger
  creeper: 1.6  # Explosive threat requiring careful positioning and timing
  pillager: 1.7  # Similar to skeleton with crossbow, predictable reload time
  magma_cube: 1.8  # Like slime but with fire damage and slightly more health
  # stage 3 [2.2, 3.4)
  stray: 2.2  # Skeleton with slowness arrows, but arrows are still blockable
  cave_spider: 2.4  # Small, fast, poison, but low health and damage
  zombified_piglin: 2.6  # Neutral unless provoked, then calls reinforcements
  # stage 4 [3.4, 5.0)
  phantom: 3.4  # Flying with dive attacks, but very predictable attack patterns
  zoglin: 3.7  # High damage and knockback, but slow and predictable
  vindicator: 4.0  # Fast, high melee damage, aggressive pursuit
  # stage 5 [5.0, 7.6)
  blaze: 5.0  # Flying, fireball barrage, fire immunity, harder to reach/hit
  enderman: 5.5  # High damage, teleportation makes it unpredictable
  witch: 6.0  # Self-healing, splash potions, poison, multiple status effects
  wither_skeleton: 6.5  # High damage, wither effect, tall reach, fire immunity
  # stage 6 [7.6, 12.0)
  ravager: 7.6  # Massive health, destroys blocks, knockback, hard to escape from
  evoker: 8.0  # Summons vex, fang attacks, multiple dangerous abilities
  vex: 10.0  # Small hitbox, phases through blocks, flying, very hard to hit
  ghast: 11.0  # Long-range explosive fireballs, flying, high health, destroys terrain

